### ISSUE TITLE
DEBUG and TEMPLATE_DEBUG settings are inverted

### ISSUE THREAD

**Issue by kevgathuku** [agiliq/django-production-ready#12]
The current setup currently produces error messages if `DEBUG` and `TEMPLATE_DEBUG` are set to `False`, which should be the other way round
I have submitted a fix in PR #11

**Comment by akshar-raaj** [comment]
@kevgathuku Merged the PR. Thanks :)

**Comment by kevgathuku** [comment]
You're welcome :+1:
